version: "3.7"
services:
  app:
    build:
      args:
        user: anshul
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: book
    container_name: book-laravel
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
    - laravel
  db:
    image: mysql:8.0
    container_name: mysql-container-book
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: bookReview
      MYSQL_ROOT_PASSWORD: book@123
      MYSQL_PASSWORD: book@123
      MYSQL_USER: anshul
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
    - laravel
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8090:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: book@123 
    networks:
    - laravel
  nginx:
    image: nginx:alpine
    container_name: nginx-container-book
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
    - laravel
networks:
  laravel:
    driver: bridge